### PR TITLE
Fix flaky CI with a complex test case

### LINKED ISSUE #103: Infinite loop when multiple stage targeting the same clusters
We got an infinite loop with the following ProgressiveSync

```
spec:
[...]
  stages:
  - maxParallel: 1
    maxTargets: 1
    name: one cluster as canary in eu-west-1
    targets:
      clusters:
        selector:
          matchLabels:
            region: eu-west-1
  - maxParallel: 3
    maxTargets: 3
    name: one cluster as canary in every other region
    targets:
      clusters:
        selector:
          matchExpression:
          - key: region
            operator: NotIn
            values:
            - eu-west-1
    name: rollout to remaining clusters
  - maxParallel: 25%
    maxTargets: 100%
    targets:
      clusters:
        selector: {}
```

After some investigation, we found the following issues:
- The scheduler relies on an annotation to determine when an Application has been synced (see https://github.com/Skyscanner/applicationset-progressive-sync/blob/main/internal/scheduler/scheduler.go#L24). While we check for the annotation, we never set it. Because of that, we never hit this code path: https://github.com/Skyscanner/applicationset-progressive-sync/blob/main/internal/scheduler/scheduler.go#L59
- We always re-write the stage status, but looking at https://github.com/Skyscanner/applicationset-progressive-sync/blob/main/api/v1alpha1/progressivesync_types.go#L107:28 we always overwrite the `StartedAt` and `FinishedAt` time
- We didn't catch this scenario in our test because our test at https://github.com/Skyscanner/applicationset-progressive-sync/blob/main/controllers/progressivesync_controller_test.go#L268 has a label selector so we return only one cluster per stage. We should change the second stage to have a label selector to include the first cluster as well.

### PR DESCRIPTION
**Pull request by nebojsa-prodana**
Fix #103 

- As discussed in #103 , the https://github.com/Skyscanner/applicationset-progressive-sync/blob/main/controllers/progressivesync_controller_test.go#L268 test has a very naive ProgressiveSync object: two stages with a selector that returns only one cluster, and targeting a single cluster at the time.

We should change this test to better reflect a real case scenario. We've internally used as default the ProgressiveSync reported in #103 so this PR change the test to use that ProgressiveSync.

In addition, I changed a couple of helpers function to be more generic for when we want to add more tests with different combination of clusters.

**TODO**

- [x] ~Fix MaxTargets to return a percentange of the remaining Out Of Sync apps instead of all the apps~ we will address this in https://github.com/Skyscanner/applicationset-progressive-sync/issues/112 because it's a quite big change
- [x] Decomment scheduler tests
- [x] Decomment removeAnnotation

This is a fork of #104 on commit cab8fff024c43a064ae7aab359f14caa14ff0f7a

### CODE REVIEW

**Comment by maruina** [comment]
We found multiple business logic issues:
- https://github.com/Skyscanner/applicationset-progressive-sync/pull/114/commits/40824ef7ca25a167a0dfb963f0c73eebeee1947e when we now re-schedule for sync the progressing application as well so we can annotate them. This protect us against a case when someone is manually syncing from the ArgoCD UI and we were not annotating the app
- https://github.com/Skyscanner/applicationset-progressive-sync/pull/114/commits/40824ef7ca25a167a0dfb963f0c73eebeee1947e we were missing a corner case in the scheduling logic 
- if the labels selector returns an empty selection, meaning `apps == nil`, we decided to make the stage as completed

File: Makefile [hunk 1]
```diff
@@ -23,7 +23,7 @@ lint: fmt vet
 
 # Run tests
 test: tools generate fmt vet manifests
-	ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover -coverprofile=../coverage.out --trace --race --progress
+	ginkgo -reportPassed -r --failOnPending --cover -coverprofile=../coverage.out --trace --race --progress
```
Comment (maruina) [inline Makefile:26]: We need to remove `-reportPassed before merging

File: internal/scheduler/scheduler.go [hunk 2]
```diff
@@ -5,11 +5,12 @@ import (
 	"github.com/Skyscanner/applicationset-progressive-sync/internal/utils"
 	argov1alpha1 "github.com/argoproj/argo-cd/pkg/apis/application/v1alpha1"
 	"github.com/argoproj/gitops-engine/pkg/health"
+	"github.com/go-logr/logr"
 	"k8s.io/apimachinery/pkg/util/intstr"
 )
 
 // Scheduler returns a list of apps to sync for a given stage
-func Scheduler(apps []argov1alpha1.Application, stage syncv1alpha1.ProgressiveSyncStage) []argov1alpha1.Application {
+func Scheduler(log logr.Logger, apps []argov1alpha1.Application, stage syncv1alpha1.ProgressiveSyncStage) []argov1alpha1.Application {
```
Comment (maruina) [inline internal/scheduler/scheduler.go:13]: We need to remove the logging before merging, or keep it as it is depending on what people feels about this.

Raise #115 to properly address this.

**Review by DimitarHristov111 — COMMENTED** [review]
We reviewed it together yesterday and the logic seems fine. We still need to verify that it works as expected using the snapshot image. There are a few comments that came up during the review and I left them below.

File: controllers/progressivesync_controller_test.go [hunk 3]
```diff
@@ -231,230 +242,501 @@ var _ = Describe("ProgressiveRollout Controller", func() {
...
+										Values:   []string{"eu-west-1"},
+									}},
+								},
+							}},
+					}, {
+						Name: "rollout to remaining clusters",
+						// MaxParallel: intstr.Parse("25%"),
+						// MaxTargets:  intstr.Parse("100%"),
+						MaxParallel: intstr.Parse("1"),
+						MaxTargets:  intstr.Parse("4"),
```
[the remark this answers is not in the document]
Comment (maruina) [reply controllers/progressivesync_controller_test.go:360]: Still doesn't work. We have https://github.com/Skyscanner/applicationset-progressive-sync/issues/112 to fix this

File: controllers/progressivesync_controller_test.go [hunk 4]
```diff
@@ -231,230 +242,501 @@ var _ = Describe("ProgressiveRollout Controller", func() {
...
+			}))
+
+			// Make sure the ProgressiveSync is completed
+			expected := ps.NewStatusCondition(syncv1alpha1.CompletedCondition, metav1.ConditionTrue, syncv1alpha1.StagesCompleteReason, "All stages completed")
+			ExpectCondition(&ps, expected.Type).Should(HaveStatus(expected.Status, expected.Reason, expected.Message))
 
-		It("should fail if unable to sync application", func() {
-			testPrefix := "failed-stages"
+			Expect(k8sClient.Delete(ctx, &ps)).To(Succeed())
+		})
```
[the remark this answers is not in the document]
Comment (maruina) [reply controllers/progressivesync_controller_test.go:691]: Removed

File: controllers/progressivesync_controller_test.go [hunk 5]
```diff
@@ -231,230 +242,501 @@ var _ = Describe("ProgressiveRollout Controller", func() {
...
+			ExpectCondition(&ps, progress.Type).Should(HaveStatus(progress.Status, progress.Reason, progress.Message))
+
+			By("completing 25% of the third stage applications")
+			Eventually(func() error {
+				return setAppStatusCompleted(ctx, "account1-eu-west-1a-2", namespace)
+			}).Should(Succeed())
+
+			// Make sure the current stage is still in progress
+			// because we still have 75% of clusters to sync
+			ExpectStageStatus(ctx, psKey, "rollout to remaining clusters").Should(MatchStage(syncv1alpha1.StageStatus{
```
[the remark this answers is not in the document]
Comment (maruina) [reply controllers/progressivesync_controller_test.go:565]: Done

File: .github/workflows/test-build.yaml [hunk 6]
```diff
@@ -38,16 +38,29 @@ jobs:
...
         run: make manager
 
-      - name: Login to GitHub Packages Docker Registry
+      - name: Docker meta
+        id: meta
+        uses: docker/metadata-action@v3
+        with:
+          # list of Docker images to use as base name for tags
+          images: |
+            ghcr.io/skyscanner/applicationset-progressive-sync
```
Comment (maruina) [inline .github/workflows/test-build.yaml:47]: We're now pushing to Github packages when opening a PR. This allow us to pull a specific docker image for e2e testing before merging it into main.

File: Makefile [hunk 7]
```diff
@@ -23,7 +23,7 @@ lint: fmt vet
 
 # Run tests
 test: tools generate fmt vet manifests
-	ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover -coverprofile=../coverage.out --trace --race --progress
+	ginkgo -r --failOnPending --cover -coverprofile=../coverage.out --trace --race --progress
```
Comment (maruina) [inline Makefile:26]: Remove the randomize options at least until we address https://github.com/Skyscanner/applicationset-progressive-sync/issues/111
Until the controller isn't scoped to a single namespace, the ginkgo random options might cause different objects to pollute the test namespace.

File: controllers/progressivesync_controller.go [hunk 8]
```diff
@@ -388,32 +383,17 @@ func (r *ProgressiveSyncReconciler) reconcileStage(ctx context.Context, ps syncv
...
-		apimeta.SetStatusCondition(ps.GetStatusConditions(), failed)
-
-		return ps, ctrl.Result{}, err
+		return ps, ctrl.Result{Requeue: true, RequeueAfter: requeueDelayOnError}, err
 	}
+	log.Info("fetched apps targeting selected clusters", "apps", utils.GetAppsName(apps))
 
 	// Get the Applications to update
-	scheduledApps := scheduler.Scheduler(apps, stage)
+	scheduledApps := scheduler.Scheduler(log, apps, stage)
```
Comment (maruina) [inline controllers/progressivesync_controller.go:391]: The scheduler logging as proved to be quite valuable. I propose we keep it in this PR and we fix-forward in https://github.com/Skyscanner/applicationset-progressive-sync/issues/115

File: controllers/progressivesync_controller_test.go [hunk 9]
```diff
@@ -745,10 +1104,10 @@ func TestSync(t *testing.T) {
 
 	testAppName := "foo-bar"
 
-	application, error := r.syncApp(ctx, testAppName)
+	application, err := r.syncApp(ctx, testAppName)
```
Comment (maruina) [inline controllers/progressivesync_controller_test.go:1107]: The IDE was complaining that `error` is a built-in package

File: controllers/progressivesync_controller.go [hunk 10]
```diff
@@ -211,14 +212,15 @@ func (r *ProgressiveSyncReconciler) requestsForSecretChange(o client.Object) []r
...
 				/*
-					Consider the following scenario:
-					- 2 Applications
-					- owned by the same ApplicationSet
-					- referenced by the same Progressive Rollout
-					- targeting the same cluster
-
-					In this scenario, we would trigger the reconciliation loop twice.
-					To avoid that, we use a map to store for which Progressive Rollout objects we already trigger the reconciliation loop.
+						Consider the following scenario:
```
Comment (sledigabel) [inline controllers/progressivesync_controller.go:215]: did `go fmt` triggered that tabbing here?

File: controllers/progressivesync_controller.go [hunk 11]
```diff
@@ -334,34 +322,41 @@ func (r *ProgressiveSyncReconciler) updateStatusWithRetry(ctx context.Context, p
...
-			r.Log.Info("Initialising empty map for Annotations")
-			latest.Annotations = make(map[string]string)
-		}
-		if val != stageName {
-			r.Log.Info("Setting the annotation for the currently progressing stage")
-			latest.Annotations[utils.ProgressiveSyncSyncedAtStageKey] = stageName
-			if err := r.Client.Update(ctx, &latest); err != nil {
-				return err
+
+		log = log.WithValues("app", fmt.Sprintf("%s/%s", app.Namespace, app.Name))
```
Comment (sledigabel) [inline controllers/progressivesync_controller.go:337]: could we use latest instead of apps here?

File: controllers/progressivesync_controller.go (hunk 10 above)
Comment (maruina) [reply controllers/progressivesync_controller.go:215]: Yes, I'm not sure why to be honest.

Comment (maruina) [reply controllers/progressivesync_controller.go:215]: I can revert it if we want.

File: controllers/progressivesync_controller.go (hunk 11 above)
Comment (maruina) [reply controllers/progressivesync_controller.go:337]: Fixed

File: controllers/progressivesync_controller.go (hunk 10 above)
Comment (sledigabel) [reply controllers/progressivesync_controller.go:215]: i was just curious :-)

File: controllers/progressivesync_controller.go [hunk 12]
```diff
@@ -388,32 +383,17 @@ func (r *ProgressiveSyncReconciler) reconcileStage(ctx context.Context, ps syncv
...
 
 	// Get the Applications to update
-	scheduledApps := scheduler.Scheduler(apps, stage)
+	scheduledApps := scheduler.Scheduler(log, apps, stage)
 
 	for _, s := range scheduledApps {
-		log.Info("syncing app", "app", s)
+		log.Info("syncing app", "app", fmt.Sprintf("%s/%s", s.Namespace, s.Name), "sync.status", s.Status.Sync.Status, "health.status", s.Status.Health.Status)
 
-		_, err := r.syncApp(ctx, s.Name)
```
Comment (sledigabel) [inline controllers/progressivesync_controller.go:416]: why was that one removed and another one at line 412 added?
If it's the same it is safer to leave the walrus operator and make sure the errors don't persist within blocks

File: internal/utils/utils.go [hunk 13]
```diff
@@ -58,15 +74,15 @@ func GetSyncedAppsByStage(apps []argov1alpha1.Application, name string) []argov1
 
 	for _, app := range apps {
 		val, ok := app.Annotations[ProgressiveSyncSyncedAtStageKey]
-		if ok && val == name && app.Status.Sync.Status == argov1alpha1.SyncStatusCodeSynced && app.Status.Health.Status == health.HealthStatusHealthy {
+		if ok && val == name && app.Status.Sync.Status == argov1alpha1.SyncStatusCodeSynced {
```
Comment (sledigabel) [inline internal/utils/utils.go:77]: what was the rationale behind this removal?

**Review by sledigabel — COMMENTED** [review]
Some small comments, overall LGTM

File: internal/utils/utils.go (hunk 13 above)
Comment (maruina) [reply internal/utils/utils.go:77]: Because the function is called `GetSyncedAppsByStage` so it should get `synced` app in the given stage - meaning it has the annotation.
The old function was also looking for the health status and we didn't need that.

File: controllers/progressivesync_controller.go [hunk 14]
```diff
@@ -334,34 +322,41 @@ func (r *ProgressiveSyncReconciler) updateStatusWithRetry(ctx context.Context, p
...
 		return nil
 	})
 	return retryErr
 }
 
 // reconcileStage reconcile a ProgressiveSyncStage
 func (r *ProgressiveSyncReconciler) reconcileStage(ctx context.Context, ps syncv1alpha1.ProgressiveSync, stage syncv1alpha1.ProgressiveSyncStage) (syncv1alpha1.ProgressiveSync, reconcile.Result, error) {
-	log := r.Log.WithValues("stage", stage.Name)
+	log := r.Log.WithValues("progressivesync", fmt.Sprintf("%s/%s", ps.Namespace, ps.Name), "applicationset", ps.Spec.SourceRef.Name, "stage", stage.Name)
+	requeueDelayOnError := time.Minute * 5
```
[the remark this answers is not in the document]
Comment (maruina) [reply controllers/progressivesync_controller.go:359]: True, made it a constant

File: controllers/progressivesync_controller.go (hunk 12 above)
Comment (maruina) [reply controllers/progressivesync_controller.go:416]: Good catch, I restored the previous commit

**Review by sledigabel — APPROVED** [review]
LGTM!
